spring:
  application:
    name: Gym_Trainer_Workload

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: https://172.18.0.5:8443/eureka/
    tls:
      enabled: true
      key-store: classpath:myCertificate.jks
      key-store-type: PKCS12
      key-store-password: rootroot
      key-password: rootroot
      trust-store: classpath:myCertificate.jks
      trust-store-type: PKCS12
      trust-store-password: rootroot